[DEFAULT]
xpath_username=//input[@id='usernameField']
xpath_password=//input[@id='passwordField']
#xpath_username=/html/body/div[1]/div[4]/div[2]/div/div/div[2]/div/form/div[2]/input
#xpath_password=/html/body/div[1]/div[4]/div[2]/div/div/div[2]/div/form/div[3]/input
xpath_loginBtn=//button[text()='Login']
