[DEFAULT]
xpath_profileBtn = /html/body/main/div/div/div[3]/div/div[3]/div[2]/a

xpath_crossClick = //div[@class='crossIcon chatBot chatBot-ic-cross']
xpath_resumeUpload = //input[@class='dummyUpload typ-14Bold']

